/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const ProjectsCreateLazyImport = createFileRoute('/projects/create')()
const AuthSignUpLazyImport = createFileRoute('/auth/signUp')()
const AuthSignInLazyImport = createFileRoute('/auth/signIn')()
const ProjectsStoriesCreateLazyImport = createFileRoute(
  '/projects/stories/create',
)()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProjectsCreateLazyRoute = ProjectsCreateLazyImport.update({
  path: '/projects/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/projects/create.lazy').then((d) => d.Route),
)

const AuthSignUpLazyRoute = AuthSignUpLazyImport.update({
  path: '/auth/signUp',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/signUp.lazy').then((d) => d.Route))

const AuthSignInLazyRoute = AuthSignInLazyImport.update({
  path: '/auth/signIn',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/signIn.lazy').then((d) => d.Route))

const ProjectsStoriesCreateLazyRoute = ProjectsStoriesCreateLazyImport.update({
  path: '/projects/stories/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/projects/stories/create.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/signIn': {
      id: '/auth/signIn'
      path: '/auth/signIn'
      fullPath: '/auth/signIn'
      preLoaderRoute: typeof AuthSignInLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/signUp': {
      id: '/auth/signUp'
      path: '/auth/signUp'
      fullPath: '/auth/signUp'
      preLoaderRoute: typeof AuthSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects/stories/create': {
      id: '/projects/stories/create'
      path: '/projects/stories/create'
      fullPath: '/projects/stories/create'
      preLoaderRoute: typeof ProjectsStoriesCreateLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
  AuthSignInLazyRoute,
  AuthSignUpLazyRoute,
  ProjectsCreateLazyRoute,
  ProjectsStoriesCreateLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/auth/signIn",
        "/auth/signUp",
        "/projects/create",
        "/projects/stories/create"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/auth/signIn": {
      "filePath": "auth/signIn.lazy.tsx"
    },
    "/auth/signUp": {
      "filePath": "auth/signUp.lazy.tsx"
    },
    "/projects/create": {
      "filePath": "projects/create.lazy.tsx"
    },
    "/projects/stories/create": {
      "filePath": "projects/stories/create.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
